### ISSUE TITLE
현재 이용가능한 부분인가요?

### ISSUE THREAD

**Issue by paul911014** [xpdlf1004/srt-macro#16]
크롬 확장프로그램이 막힘에 따라 여쭈어봅니다

현재 이용가능한 프로그램인가요?

혹시 이용가능하다면 사용법은 어떻게 되는가요?

**Comment by xpdlf1004** [comment]
이용 가능하구요 사용법은 해보시면 간단합니다.
https://github.com/xpdlf1004/srt-macro/releases
